stages:
  - build
  - test
  - deploy

building-application:
  stage: build
  image: node:latest
  script: 
    - npm install -g @angular/cli
    - npm install
    - ng build --prod

testing-application:
  stage: test
  image: node:latest
  script:
    - echo 'Testing app...'

deploying-application:
  stage: deploy
  image: node:latest
  script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli
    - ng build --prod
    - firebase deploy --token $FIREBASE_TOKEN