image: node:latest
 
stages:
  - build
  - test
  - deploy

before_script:
  - npm install -g @angular/cli

building-application:
  stage: build
  script: 
    - npm install
    - ng build --prod
  cache:
    paths:
      - dist/
      - node_modules/

testing-application:
  stage: test
  script:
    - ng test --browsers PhantomJS --watch=false

deploying-application:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN