image: node:latest
 
stages:
  - build
  - test
  - staging
  - production

before_script:
  - npm install
  - npm install -g @angular/cli

build-application:
  stage: build
  artifacts:
    paths:
      - dist/
  script: 
    - npm install
    - ng build --prod

test-application:
  stage: test
  script:
    - ng test --browsers PhantomJS --watch=false

deploy-application:
  stage: staging
  dependencies:
    - build-application
  script:
    - npm install -g firebase-tools
    - echo "Deploying to Firebase"
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - /^feature\/*

deploy-prod:
  stage: production
  dependencies:
    - build-application
  script:
    - echo "Deploying to fancy AWS server"
  only:
    - master