image: node:latest
 
stages:
  - build
  - test
  - deploy

before_script:
  - npm install -g @angular/cli
  - npm install

building-application:
  stage: build
  script: 
    - ng build --prod

testing-application:
  stage: test
  script:
    - ng test --browsers PhantomJS --watch=false

deploying-application:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - ng build --prod
    - firebase deploy --token $FIREBASE_TOKEN