stages:
  - build
  - test
  - deploy

before_script:
  - npm install -g @angular/cli
  - npm install

building-application:
  stage: build
  image: node:latest
  script: 
    - ng build --prod

testing-application:
  stage: test
  image: node:latest
  script:
    - ng test

deploying-application:
  stage: deploy
  image: node:latest
  script:
    - npm install -g firebase-tools
    - ng build --prod
    - firebase deploy --token $FIREBASE_TOKEN