image: node:latest
 
stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

building-application:
  stage: build
  script: 
    - npm install
    - ng build --prod

testing-application:
  stage: test
  script:
    - ng test --browsers PhantomJS --watch=false

deploying-application:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - ng build --prod
    - firebase deploy --token $FIREBASE_TOKEN